name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: dart format lib test --set-exit-if-changed

      - name: Analyze
        run: flutter analyze lib test